//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ReservationDBContext : DbContext
    {
        public ReservationDBContext()
            : base("name=ReservationDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblreservation> tblreservations { get; set; }
        public virtual DbSet<tbltable> tbltables { get; set; }
        public virtual DbSet<tblProfile> tblProfiles { get; set; }
        public virtual DbSet<tblAdmin> tblAdmins { get; set; }
    
        public virtual ObjectResult<Nullable<int>> spAddReservation(string name, string phonenumber, string email, string date, string time, Nullable<int> partysize, string specialnotes)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var phonenumberParameter = phonenumber != null ?
                new ObjectParameter("phonenumber", phonenumber) :
                new ObjectParameter("phonenumber", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var dateParameter = date != null ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(string));
    
            var timeParameter = time != null ?
                new ObjectParameter("time", time) :
                new ObjectParameter("time", typeof(string));
    
            var partysizeParameter = partysize.HasValue ?
                new ObjectParameter("partysize", partysize) :
                new ObjectParameter("partysize", typeof(int));
    
            var specialnotesParameter = specialnotes != null ?
                new ObjectParameter("specialnotes", specialnotes) :
                new ObjectParameter("specialnotes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spAddReservation", nameParameter, phonenumberParameter, emailParameter, dateParameter, timeParameter, partysizeParameter, specialnotesParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spCancelReservation(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spCancelReservation", idParameter);
        }
    
        public virtual ObjectResult<spViewReservation_Result> spViewReservation(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spViewReservation_Result>("spViewReservation", idParameter);
        }
    
        public virtual ObjectResult<spViewReservations_Result> spViewReservations()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spViewReservations_Result>("spViewReservations");
        }
    
        public virtual int spUpdateReservation(Nullable<int> id, string name, string phonenumber, string email, string date, string time, Nullable<int> partysize, string specialnotes)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var phonenumberParameter = phonenumber != null ?
                new ObjectParameter("phonenumber", phonenumber) :
                new ObjectParameter("phonenumber", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var dateParameter = date != null ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(string));
    
            var timeParameter = time != null ?
                new ObjectParameter("time", time) :
                new ObjectParameter("time", typeof(string));
    
            var partysizeParameter = partysize.HasValue ?
                new ObjectParameter("partysize", partysize) :
                new ObjectParameter("partysize", typeof(int));
    
            var specialnotesParameter = specialnotes != null ?
                new ObjectParameter("specialnotes", specialnotes) :
                new ObjectParameter("specialnotes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateReservation", idParameter, nameParameter, phonenumberParameter, emailParameter, dateParameter, timeParameter, partysizeParameter, specialnotesParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spAddReservation1(string name, string phonenumber, string email, string date, string time, Nullable<int> partysize, string specialnotes)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var phonenumberParameter = phonenumber != null ?
                new ObjectParameter("phonenumber", phonenumber) :
                new ObjectParameter("phonenumber", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var dateParameter = date != null ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(string));
    
            var timeParameter = time != null ?
                new ObjectParameter("time", time) :
                new ObjectParameter("time", typeof(string));
    
            var partysizeParameter = partysize.HasValue ?
                new ObjectParameter("partysize", partysize) :
                new ObjectParameter("partysize", typeof(int));
    
            var specialnotesParameter = specialnotes != null ?
                new ObjectParameter("specialnotes", specialnotes) :
                new ObjectParameter("specialnotes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spAddReservation1", nameParameter, phonenumberParameter, emailParameter, dateParameter, timeParameter, partysizeParameter, specialnotesParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spAddReservation_AutoAssignOff(string name, string phonenumber, string email, string date, string time, Nullable<int> partysize, string specialnotes, Nullable<int> tableno)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var phonenumberParameter = phonenumber != null ?
                new ObjectParameter("phonenumber", phonenumber) :
                new ObjectParameter("phonenumber", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var dateParameter = date != null ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(string));
    
            var timeParameter = time != null ?
                new ObjectParameter("time", time) :
                new ObjectParameter("time", typeof(string));
    
            var partysizeParameter = partysize.HasValue ?
                new ObjectParameter("partysize", partysize) :
                new ObjectParameter("partysize", typeof(int));
    
            var specialnotesParameter = specialnotes != null ?
                new ObjectParameter("specialnotes", specialnotes) :
                new ObjectParameter("specialnotes", typeof(string));
    
            var tablenoParameter = tableno.HasValue ?
                new ObjectParameter("tableno", tableno) :
                new ObjectParameter("tableno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spAddReservation_AutoAssignOff", nameParameter, phonenumberParameter, emailParameter, dateParameter, timeParameter, partysizeParameter, specialnotesParameter, tablenoParameter);
        }
    
        public virtual ObjectResult<spViewProfile_Result> spViewProfile()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spViewProfile_Result>("spViewProfile");
        }
    
        public virtual int spUpdateProfile(string name, string email, string contactno, string autoassign, string restaurantaddress, string timings)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var contactnoParameter = contactno != null ?
                new ObjectParameter("contactno", contactno) :
                new ObjectParameter("contactno", typeof(string));
    
            var autoassignParameter = autoassign != null ?
                new ObjectParameter("autoassign", autoassign) :
                new ObjectParameter("autoassign", typeof(string));
    
            var restaurantaddressParameter = restaurantaddress != null ?
                new ObjectParameter("restaurantaddress", restaurantaddress) :
                new ObjectParameter("restaurantaddress", typeof(string));
    
            var timingsParameter = timings != null ?
                new ObjectParameter("timings", timings) :
                new ObjectParameter("timings", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateProfile", nameParameter, emailParameter, contactnoParameter, autoassignParameter, restaurantaddressParameter, timingsParameter);
        }
    
        public virtual ObjectResult<spViewContacts_Result> spViewContacts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spViewContacts_Result>("spViewContacts");
        }
    
        public virtual int spAssigntable(Nullable<int> tableno, string time, Nullable<int> id)
        {
            var tablenoParameter = tableno.HasValue ?
                new ObjectParameter("tableno", tableno) :
                new ObjectParameter("tableno", typeof(int));
    
            var timeParameter = time != null ?
                new ObjectParameter("time", time) :
                new ObjectParameter("time", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAssigntable", tablenoParameter, timeParameter, idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spAuthenticateUser(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spAuthenticateUser", emailParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spRegisterUser(string userName, string password, string email)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spRegisterUser", userNameParameter, passwordParameter, emailParameter);
        }
    
        public virtual ObjectResult<spOpenSeating_Result> spOpenSeating()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spOpenSeating_Result>("spOpenSeating");
        }
    }
}
