//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProfile
    {
        public string name { get; set; }
        public string email { get; set; }
        public string contactno { get; set; }
        public string autoassign { get; set; }
        public string RestaurantAddress { get; set; }
        public string timings { get; set; }
    }
}
