//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltable
    {
        public int tableno { get; set; }
        public string status { get; set; }
        public Nullable<int> size { get; set; }
        public string time { get; set; }
        public Nullable<int> id { get; set; }

            }
}
